# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=1000)),
                ('event_description', models.CharField(max_length=1000)),
                ('facebook_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('event_relation', models.CharField(max_length=1000)),
                ('points', models.IntegerField(default=0)),
                ('events_attended', models.ManyToManyField(blank=True, related_name='events', to='gamify.Event')),
            ],
        ),
    ]
