# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='event_relation',
        ),
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=5),
        ),
    ]
